### ISSUE TITLE
Just installed, shows a bunch of errors on vim startup

### ISSUE THREAD

**Issue by thefzsalam** [dbsr/vimpy#4]
Errors:

```
Error detected while processing /home/farzeen/.vim/plugged/vimpy/ftplugin/python/vimpy.vim:
line   28:
Traceback (most recent call last):
  File "<string>", line 4, in <module>
vim.error: Vim:E121: Undefined variable: let
line   43:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/farzeen/.vim/plugged/vimpy/ftplugin/python/vimpy/vimpy_.py", line 9, in <module>
    from pyflakes import reporter, api
ImportError: No module named pyflakes

```

**Comment by dbsr** [comment]
Hi farseenabdulsalam, this is a pretty old (inactive) plugin.

Have you read the readme and installed pyflakes?

Vimpy relies on 'pyflakes' for its missing import decection magic. This third-party module can be installed using pip or downloaded from pypi: https://pypi.python.org/pypi/pyflakes.

**Comment by thefzsalam** [comment]
I guess I have them installed
$ pacman -Ss pyflakes
community/flake8 1:2.5.4-2 [installed]
    The modular source code checker: pep8, pyflakes and co
community/python-pyflakes 1.1.0-1 [installed]
    A lint-like tool for Python to identify common errors quickly without executing code
community/python2-flake8 1:2.5.4-2
    The modular source code checker: pep8, pyflakes and co
community/python2-pyflakes 1.1.0-1
    A lint-like tool for Python to identify common errors quickly without executing code

**Comment by jorgemdnt** [comment]
@farseenabdulsalam you have to install it using pip. just found this plugin and it worked for me.
